config/routes.rb
Rails.application.routes.draw do
  resources :produtos do
  	resources :upsell do
      resources :promocoes
    end
  	resources :paginas
  end
  resources :administradores
  root to: 'produtos#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  get '/login', to: 'login#index'

  get '/upsell/:pagina_id', to: 'funil#upsell'

  post '/99run/login/comprar/grupo-corrida', to: 'acao99run#login_compra_grupo_corrida'
  post '/99run/inscricao-email', to: 'acao99run#captura_email'
  post '/99run/inscricao-telefone', to: 'acao99run#captura_telefone'
  
  get '/:slug_produto/:slug_pagina', to: 'funil#slug'
end

app/models/pagina.rb
class Pagina < ApplicationRecord
  belongs_to :produto

  def self.iniciais(produto_id)
  	paginas = Pagina.where(produto_id: produto_id, inicio: true)
  end

  def proxima_pagina
  	Pagina.find(self.pagina_id)
  rescue
    nil
  end

  def upsell
    Upsell.find(self.upsell_id)
  rescue
    nil
  end

  def proximas_paginas
  	return [] if self.pagina_id.blank?
    paginas = Pagina.where(id: self.pagina_id)
    if paginas.present?
  	  return [paginas.first]
    else
      return []
    end
  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  before_action :set_pagina, only: [:show, :edit, :update, :destroy]
  before_action :set_produto

  # GET /paginas
  # GET /paginas.json
  def index
    @paginas = Pagina.iniciais(@produto.id)
  end

  # GET /paginas/1
  # GET /paginas/1.json
  def show
  end

  # GET /paginas/new
  def new
    @pagina = Pagina.new
  end

  # GET /paginas/1/edit
  def edit
  end

  # POST /paginas
  # POST /paginas.json
  def create
    @pagina = Pagina.new(pagina_params)
    @pagina.produto = @produto

    respond_to do |format|
      if @pagina.save
        format.html { redirect_to edit_produto_pagina_path(@produto, @pagina), notice: 'Pagina was successfully created.' }
        format.json { render :show, status: :created, location: @pagina }
      else
        format.html { render :new }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paginas/1
  # PATCH/PUT /paginas/1.json
  def update
    respond_to do |format|
      if @pagina.update(pagina_params)
        format.html { redirect_to edit_produto_pagina_path(@produto, @pagina), notice: 'Pagina was successfully updated.' }
        format.json { render :show, status: :ok, location: @pagina }
      else
        format.html { render :edit }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paginas/1
  # DELETE /paginas/1.json
  def destroy
    @pagina.destroy
    respond_to do |format|
      format.html { redirect_to produto_paginas_path(@produto), notice: 'Pagina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_produto
      @produto = Produto.find(params[:produto_id])
    end

    def set_pagina
      @pagina = Pagina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagina_params
      params.require(:pagina).permit(:nome, :slug, :conteudo, :produto_id, :pagina_id, :inicio, :upsell_id, :valido_com_cupom, :cupom_opcional)
    end
end

app/views/paginas/_form.html.erb
<%= form_for([@produto, @pagina], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @pagina.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo:</h4>

      <ul>
      <% @pagina.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :inicio, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :inicio, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :slug, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :slug, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valido_com_cupom, "Precisa de cupom? (Obrigatório)", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :valido_com_cupom, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cupom_opcional, "Precisa de cupom? (Opcional)", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :cupom_opcional, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :conteudo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :conteudo, class: "form-control", style: "height: 600px" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :upsell_id, "Próxima upsell", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <select class="form-control" id="pagina_upsell_id" name="pagina[upsell_id]">
        <option value="">[Selecione]</option>
        <% Upsell.all.each do |upsell| %>
          <option value="<%= upsell.id %>" <% if @pagina.upsell_id == upsell.id %>selected="selected"<% end %>><%= upsell.nome %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pagina_id, "Próxima pagina", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <select class="form-control" id="pagina_pagina_id" name="pagina[pagina_id]">
        <option value="">[Selecione]</option>
        <% Pagina.where("inicio is null or inicio = false").each do |pagina| %>
          <% next if @pagina.id == pagina.id %>
          <option value="<%= pagina.id %>" <% if @pagina.pagina_id == pagina.id %>selected="selected"<% end %>><%= pagina.nome %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/paginas/_pagina.html.erb
<% if paginas.present? %>
<ul style="padding: 20px;">
  <% paginas.each do |pagina| %>
    <li>
      <div><b>Nome</b> <%= pagina.nome %></div>
      <div><b>Slug</b> <%= pagina.slug %> <a href="/<%= @produto.slug %>/<%= pagina.slug %>" target="_blank">Ver</a></div>
      <% if pagina.upsell.present? %>
        <div><b>Upsell</b> <%= pagina.upsell.nome %> <a href="/produtos/<%= pagina.produto.id %>/upsell/<%= pagina.upsell.id %>/edit">Ir</a></div> 
      <% end %>
      <div>
        <%= link_to 'Mostrar', produto_pagina_path(@produto, pagina), class:"btn btn-primary" %>
        <%= link_to 'Editar', edit_produto_pagina_path(@produto, pagina), class:"btn btn-warning" %>
        <%= link_to 'Apagar', produto_pagina_path(@produto, pagina), class:"btn btn-danger", method: :delete, data: { confirm: 'Confirma?' } %>
      </div>
      <%= render 'pagina', {paginas: pagina.proximas_paginas} %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/paginas/edit.html.erb
<div class="page-header">
  <%= link_to produto_paginas_path(@produto), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to produto_pagina_path(@produto, @pagina), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando pagina</h1>
</div>

<%= render 'form' %>

app/views/paginas/index.html.erb
<div class="page-header">
  <%= link_to new_produto_pagina_path(@produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Pagina
  <% end %>
  <%= link_to produtos_path, class: 'btn btn-primary' do %>
    Produtos
  <% end %>
  <h1>Listando paginas do produto <%= @produto.nome %></h1>
</div>

<div class="table-responsive">
  <%= render 'pagina', {paginas: @paginas} %>
</div>

app/views/paginas/new.html.erb
<div class="page-header">
  <%= link_to produto_paginas_path(@produto), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo pagina</h1>
</div>

<%= render 'form' %>

app/views/paginas/show.html.erb
<div class="page-header">
  <%= link_to produto_paginas_path(@produto), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_produto_pagina_path(@produto, @pagina), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar pagina</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @pagina.nome %></dd>
  <dt>Slug:</dt>
  <dd><%= @pagina.slug %></dd>
  <dt>Conteudo:</dt>
  <dd><%= @pagina.conteudo %></dd>
  <dt>Produto:</dt>
  <dd><%= @pagina.produto %></dd>
</dl>