config/routes.rb
Rails.application.routes.draw do
  resources :produtos do
  	resources :upsell do
      resources :promocoes
    end
  	resources :paginas
  end
  resources :administradores
  root to: 'produtos#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  get '/login', to: 'login#index'

  get '/upsell/:pagina_id', to: 'funil#upsell'

  post '/99run/login/comprar/grupo-corrida', to: 'acao99run#login_compra_grupo_corrida'
  post '/99run/inscricao-email', to: 'acao99run#captura_email'
  post '/99run/inscricao-telefone', to: 'acao99run#captura_telefone'
  
  get '/:slug_produto/:slug_pagina', to: 'funil#slug'
end

app/controllers/administradores_controller.rb
class AdministradoresController < ApplicationController
  before_action :set_administrador, only: [:show, :edit, :update, :destroy]
  # skip_before_action :guest_request
  # GET /administradores
  # GET /administradores.json
  def index
    @administradores = Administrador.all
  end

  # GET /administradores/1
  # GET /administradores/1.json
  def show
  end

  # GET /administradores/new
  def new
    @administrador = Administrador.new
  end

  # GET /administradores/1/edit
  def edit
  end

  # POST /administradores
  # POST /administradores.json
  def create
    @administrador = Administrador.new(administrador_params)

    respond_to do |format|
      if @administrador.save
        format.html { redirect_to @administrador, notice: 'Administrador was successfully created.' }
        format.json { render :show, status: :created, location: @administrador }
      else
        format.html { render :new }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradores/1
  # PATCH/PUT /administradores/1.json
  def update
    respond_to do |format|
      if @administrador.update(administrador_params)
        format.html { redirect_to @administrador, notice: 'Administrador was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrador }
      else
        format.html { render :edit }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradores/1
  # DELETE /administradores/1.json
  def destroy
    @administrador.destroy
    respond_to do |format|
      format.html { redirect_to administradores_url, notice: 'Administrador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrador
      @administrador = Administrador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrador_params
      params.require(:administrador).permit(:nome, :email, :senha)
    end
end

app/views/administradores/_form.html.erb
<%= form_for(@administrador, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @administrador.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo:</h4>

      <ul>
      <% @administrador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :senha, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :senha, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/administradores/edit.html.erb
<div class="page-header">
  <%= link_to administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @administrador, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando administrador</h1>
</div>

<%= render 'form' %>

app/views/administradores/index.html.erb
<div class="page-header">
  <%= link_to new_administrador_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Administrador
  <% end %>
  <h1>Listando administradores</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @administradores) do |administrador| %>
        <td><%= administrador.nome %></td>
        <td><%= administrador.email %></td>
        <td><%= link_to 'Mostrar', administrador %></td>
        <td><%= link_to 'Editar', edit_administrador_path(administrador) %></td>
        <td><%= link_to 'Apagar', administrador, method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/administradores/new.html.erb
<div class="page-header">
  <%= link_to administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo administrador</h1>
</div>

<%= render 'form' %>

app/views/administradores/show.html.erb
<div class="page-header">
  <%= link_to administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_administrador_path(@administrador), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar administrador</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @administrador.nome %></dd>
  <dt>Email:</dt>
  <dd><%= @administrador.email %></dd>
  <dt>Senha:</dt>
  <dd><%= @administrador.senha %></dd>
</dl>