config/routes.rb
Rails.application.routes.draw do
  resources :produtos do
  	resources :upsell do
      resources :promocoes
    end
  	resources :paginas
  end
  resources :administradores
  root to: 'produtos#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  get '/login', to: 'login#index'

  get '/upsell/:pagina_id', to: 'funil#upsell'

  post '/99run/login/comprar/grupo-corrida', to: 'acao99run#login_compra_grupo_corrida'
  post '/99run/inscricao-email', to: 'acao99run#captura_email'
  post '/99run/inscricao-telefone', to: 'acao99run#captura_telefone'
  
  get '/:slug_produto/:slug_pagina', to: 'funil#slug'
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :url, :slug)
    end
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @produto.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo:</h4>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :slug, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :slug, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @produto, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/index.html.erb
<div class="page-header">
  <%= link_to new_produto_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Produto
  <% end %>
  <h1>Listando produtos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Slug</th>
        <th>Url</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @produtos) do |produto| %>
        <td><%= produto.nome %></td>
        <td><%= produto.slug %></td>
        <td><%= produto.url %></td>
        <td><a href="/produtos/<%= produto.id %>/paginas">Paginas</a></td>
        <td><a href="/produtos/<%= produto.id %>/upsell">Upsell</a></td>
        <td><%= link_to 'Mostrar', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Apagar', produto, method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/produtos/new.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/show.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_produto_path(@produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar produto</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @produto.nome %></dd>
  <dt>Url:</dt>
  <dd><%= @produto.url %></dd>
</dl>