config/routes.rb
Rails.application.routes.draw do
  resources :produtos do
  	resources :upsell do
      resources :promocoes
    end
  	resources :paginas
  end
  resources :administradores
  root to: 'produtos#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  get '/login', to: 'login#index'

  get '/upsell/:pagina_id', to: 'funil#upsell'

  post '/99run/login/comprar/grupo-corrida', to: 'acao99run#login_compra_grupo_corrida'
  post '/99run/inscricao-email', to: 'acao99run#captura_email'
  post '/99run/inscricao-telefone', to: 'acao99run#captura_telefone'
  
  get '/:slug_produto/:slug_pagina', to: 'funil#slug'
end

app/models/upsell.rb
class Upsell < ApplicationRecord
  belongs_to :produto
  has_many :promocoes, :dependent => :delete_all
end

app/controllers/upsell_controller.rb
class UpsellController < ApplicationController
  before_action :set_upsell, only: [:show, :edit, :update, :destroy]
  before_action :set_produto

  # GET /upsell
  # GET /upsell.json
  def index
    @upsell = Upsell.where(produto_id: @produto.id)
  end

  # GET /upsell/1
  # GET /upsell/1.json
  def show
  end

  # GET /upsell/new
  def new
    @upsell = Upsell.new
  end

  # GET /upsell/1/edit
  def edit
  end

  # POST /upsell
  # POST /upsell.json
  def create
    @upsell = Upsell.new(upsell_params)
    @upsell.produto = @produto

    respond_to do |format|
      if @upsell.save
        format.html { redirect_to produto_upsell_index_path(@produto), notice: 'Upsell was successfully created.' }
        format.json { render :show, status: :created, location: @upsell }
      else
        format.html { render :new }
        format.json { render json: @upsell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upsell/1
  # PATCH/PUT /upsell/1.json
  def update
    respond_to do |format|
      if @upsell.update(upsell_params)
        format.html { redirect_to produto_upsell_index_path(@produto), notice: 'Upsell was successfully updated.' }
        format.json { render :show, status: :ok, location: @upsell }
      else
        format.html { render :edit }
        format.json { render json: @upsell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upsell/1
  # DELETE /upsell/1.json
  def destroy
    @upsell.destroy
    respond_to do |format|
      format.html { redirect_to produto_upsell_index_path(@produto), notice: 'Upsell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_produto
      @produto = Produto.find(params[:produto_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_upsell
      @upsell = Upsell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upsell_params
      params.require(:upsell).permit(:produto_id, :data_inicial, :data_final, :somente_boleto, :somente_cartao, :tentar_a_cada_compra, :mostrar_para_compras_acima_de, :mostrar_para_compras_ate, :nome)
    end
end

app/views/upsell/_form.html.erb
<%= form_for([@produto, @upsell], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @upsell.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os erros abaixo:</h4>

      <ul>
      <% @upsell.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_inicial, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :data_inicial, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data_final, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :data_final, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :somente_boleto, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :somente_boleto, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :somente_cartao, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :somente_cartao, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tentar_a_cada_compra, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :tentar_a_cada_compra, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mostrar_para_compras_acima_de, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :mostrar_para_compras_acima_de, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mostrar_para_compras_ate, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :mostrar_para_compras_ate, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/upsell/edit.html.erb
<div class="page-header">
  <%= link_to produto_upsell_index_path(@produto), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to produto_upsell_path(@produto, @upsell), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando upsell</h1>
</div>

<%= render 'form' %>

app/views/upsell/index.html.erb
<div class="page-header">
  <%= link_to new_produto_upsell_path(@produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Upsell
  <% end %>
  <%= link_to produtos_path, class: 'btn btn-primary' do %>
    Produtos
  <% end %>
  <h1>Listando upsell do produto <%= @produto.nome %></h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Data inicial</th>
        <th>Data final</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @upsell) do |upsell| %>
        <td><%= upsell.nome %></td>
        <td><%= upsell.data_inicial.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= upsell.data_final.strftime("%d/%m/%Y %H:%M")  %></td>
        <td><%= link_to 'Promoções', produto_upsell_promocoes_path(@produto, upsell) %></td>
        <td><%= link_to 'Mostrar', produto_upsell_path(@produto, upsell) %></td>
        <td><%= link_to 'Editar', edit_produto_upsell_path(@produto, upsell) %></td>
        <td><%= link_to 'Apagar', produto_upsell_path(@produto, upsell), method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/upsell/new.html.erb
<div class="page-header">
  <%= link_to produto_upsell_index_path(@produto), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo upsell</h1>
</div>

<%= render 'form' %>

app/views/upsell/show.html.erb
<div class="page-header">
  <%= link_to produto_upsell_index_path(@produto), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_produto_upsell_path(@produto, @upsell), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar upsell</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @upsell.nome %></dd>
  <dt>Produto:</dt>
  <dd><%= @upsell.produto.nome %></dd>
  <dt>Data inicial:</dt>
  <dd><%= @upsell.data_inicial %></dd>
  <dt>Data final:</dt>
  <dd><%= @upsell.data_final %></dd>
  <dt>Somente boleto:</dt>
  <dd><%= @upsell.somente_boleto %></dd>
  <dt>Somente cartao:</dt>
  <dd><%= @upsell.somente_cartao %></dd>
  <dt>Tentar a cada compra:</dt>
  <dd><%= @upsell.tentar_a_cada_compra %></dd>
  <dt>Mostrar para compras acima de:</dt>
  <dd><%= @upsell.mostrar_para_compras_acima_de %></dd>
  <dt>Mostrar para compras ate:</dt>
  <dd><%= @upsell.mostrar_para_compras_ate %></dd>
</dl>